Layout
TI-proftaak-MB-A3/android-app pull request #5
Opened 2021-06-01 11:34 UTC by Ewoodss

Medal view
Home Screen
Colors added
begin van code verificatie

2021-06-01 11:38 UTC, JustRostin commented on app/src/main/java/nl/avans/ti/MainActivity.java
> +            Toast.makeText(view.getContext(), "de code moet 4 cijfers lang zijn", Toast.LENGTH_LONG).show();
De code moet 6 cijfers lang zijn
```suggestion
            Toast.makeText(view.getContext(), "de code moet 6 cijfers lang zijn", Toast.LENGTH_LONG).show();
```

2021-06-01 11:39 UTC, JustRostin commented on app/src/main/java/nl/avans/ti/MainActivity.java
> +            Log.d(String.valueOf(view.getTag()), "value entered didn't meet the requirments");
Geen fixed strings maar vanuit translation (values)

2021-06-01 11:42 UTC, JustRostin requested changes
Zie opmerkingen @Ewoodss

2021-06-01 11:42 UTC, JustRostin commented on app/src/main/java/nl/avans/ti/Medal/MedalActivity.java
> +            this.attractions.add(new Attraction(R.drawable.efteling_vl_hollander, "Vliegende hollander " + i, R.drawable.check_failed, R.drawable.medal_progres));
Geen fixed string

2021-06-01 11:42 UTC, JustRostin commented on app/src/main/java/nl/avans/ti/MainActivity.java
> +            Log.d(String.valueOf(view.getTag()), "value entered didn't meet the requirments");
Geen fixed strings altijd vanuit translations werken

2021-06-01 11:42 UTC, JustRostin commented on app/src/main/java/nl/avans/ti/MainActivity.java
> +            Toast.makeText(view.getContext(), "de code moet 4 cijfers lang zijn", Toast.LENGTH_LONG).show();
```suggestion
            Toast.makeText(view.getContext(), "de code moet 6 cijfers lang zijn", Toast.LENGTH_LONG).show();
```

2021-06-01 11:43 UTC, Ewoodss commented on app/src/main/java/nl/avans/ti/MainActivity.java
> +            Toast.makeText(view.getContext(), "de code moet 4 cijfers lang zijn", Toast.LENGTH_LONG).show();
is al aangepast in volgende commit

2021-06-03 07:03 UTC, JustRostin approved these changes

2021-06-03 07:05 UTC, merged